### ISSUE TITLE
Update scripts to use f-strings for clarity

### ISSUE THREAD

**Issue by damian-romero** [UAL-RE/ReQUIAM_csv#56]
Currently, scripts are using `.format()` for strings.

While this ok, the pythonic way prefers f-strings for their readability
and several other reasons. (See Item 4 in [Effective Python](https://effectivepython.com/))

Example:

```python
log.info("   {} : {}".format(dept.loc[bb], bb + off))

## Change to:

log.info(f"   {dept.loc[bb]} : {bb + off}")
```

This can be a good first issue implemented as a feature for the next release.

**Comment by 96RadhikaJadhav** [comment]
Hi @damian-romero  Can I work on it?

**Comment by damian-romero** [comment]
Hi @96RadhikaJadhav ! Unfortunately we've decided not to touch this code for the time being. Thanks for your interest though!
