### ISSUE TITLE
Enhancement: Migrate repository to UAL-ODIS

### ISSUE THREAD

**Issue by astrochun** [UAL-RE/ReQUIAM_csv#71]
**Summary**
It's been decided to migrate from ualibraries to UAL-ODIS.

**Objectives**
Full transfer with branches, issues, PR and project boards. Settings may need to be manually transfer over

**Proposal**
- [x] Move forked copy from UAL-ODIS to a personal copy. I suggest mine
- [x] Perform transfer and confirm transfer was successful
- [x] Update local dev environments
    - [x] Chun's
    - [x] Damian's
- [x] Update ReQUIAM for new deployment path ([Issue no. 137](https://github.com/ualibraries/ReQUIAM/issues/137))

*Testing notes*
Already tested transfer [here](https://github.com/UAZCovidData/ODIS-test-transfer-repo)

No branch deployment here.

**Comment by damian-romero** [comment]
@astrochun you asked me to create this issue, but we forgot you had created it last week in our triage meeting. I have updated the description and I'm closing it now.
