### ISSUE TITLE
Docs: Update README.md to Avoid Duplicates with Docs

### ISSUE THREAD

**Issue by damian-romero** [UAL-RE/ReQUIAM_csv#75]
**Describe the hotfix**
README.md contains duplicate sections from our Read the Docs documentation. The task is to simplify the maintenance of README.md by one of three methods:

1) Using the external library [m2r2](https://github.com/sphinx-doc/sphinx/issues/7000#issuecomment-677916705) to generate ../../README.md from source/. Drawback: it hasn't been maintained for a few months now. 

2) Using the external library [MyST parser](https://github.com/executablebooks/myst-parser) as in (1). This library seems more up-to-date. 

3) Simply stripping sections that need constant maintenance, such as code and Python versions. Then, update the TOC with links to our RTDs, for instance:

`- [Getting Started](https://requiam_csv.readthedocs.io/en/latest/gettinnstarted.html)`

**Issue**: if the links to RTDs are implemented before merging #66 into master, we will not be able to properly test them because they use the "/latest/" path.

**Version information**
 - ReQUIAM_csv version: [0.11.1]

*Plan of action*

1. Strip the following sections from README.md:
```
- Getting Started
    - Requirements
    - Installation Instructions
    - Configuration Settings
    - Testing Installation
- Execution
    - Workflow
- Versioning
```
2. Add RTDs links to each of those sections in the TOC, for instance:
```
https://requiam_csv.readthedocs.io/en/latest/GettingStarted.html
https://requiam_csv.readthedocs.io/en/latest/GettingStarted.html#requirements
https://requiam_csv.readthedocs.io/en/latest/GettingStarted.html#installation-instructions
https://requiam_csv.readthedocs.io/en/latest/GettingStarted.html#configuration-settings
https://requiam_csv.readthedocs.io/en/latest/GettingStarted.html#testing-installation
https://requiam_csv.readthedocs.io/en/latest/Execution.html
https://requiam_csv.readthedocs.io/en/latest/Execution.html#workflow
...etc
```
3. Add a message before the TOC to show where the full documentation lives:
```
## Developers' note:

Full documentation for this code is available on
[Read the Docs](https://requiam_csv.readthedocs.io/en/latest/). The table of contents below links to the appropriate sections within our Read the Docs documentation.
```
*Additional context*

@astrochun: **This can be implemented as a simple PR that will be merged but without any bumping**

**Implemented in**: >= v0.12.4

**Comment by damian-romero** [comment]
I've added the `p2` label to reflect that this change must be implemented after v0.12.0 is released

**Comment by astrochun** [comment]
Note: There's an `m2r2` library that would allow sphinx to import README.md. Not tested but see:  https://github.com/sphinx-doc/sphinx/issues/7000#issuecomment-677916705

**Comment by damian-romero** [comment]
> Note: There's an `m2r2` library that would allow sphinx to import README.md. Not tested but see: [sphinx-doc/sphinx#7000 (comment)](https://github.com/sphinx-doc/sphinx/issues/7000#issuecomment-677916705)

Looks good. So does [MyST parser](https://myst-parser.readthedocs.io/en/latest/) and it seems better maintained. I'll give them a try and fall back into the simplifying README.md if everything else fails. I have updated the description for this issue

**Comment by damian-romero** [comment]
Unassigning myself. I recommend simplifying this issue as we did on redata-commons [`Update README.md for Sphinx documentation #9`](https://github.com/UAL-ODIS/redata-commons/issues/9).
